"""Turn a :class:`ProcessIR` into a runnable Python + Playwright project.

Implementation note — Jinja proved fragile for generating indented Python
inside nested ``for`` blocks (trim/lstrip combinations that keep the
``main.py`` skeleton valid also eat the function-body indentation we need
for ``process_<tx>.py``). We build the three Python files as plain strings
here, keep Jinja for ``pyproject.toml`` / ``README.md`` where the output
format is looser.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

from rpa_architect.ir.schema import ProcessIR, Step, Transaction, UIAction
from rpa_architect.migrator.activity_map import (
    UnsupportedActionError,
    emit_call,
)
from rpa_architect.migrator.selector_translator import translate_selector

TEMPLATES_DIR = Path(__file__).resolve().parents[3] / "templates" / "migrator"


def emit_project(ir: ProcessIR, output_dir: Path | str) -> None:
    """Render the full project into ``output_dir``."""
    out = Path(output_dir)
    (out / "processes").mkdir(parents=True, exist_ok=True)
    (out / "tests").mkdir(parents=True, exist_ok=True)

    views = [_transaction_view(tx) for tx in ir.transactions]

    (out / "main.py").write_text(_render_main(ir.process_name, views))
    for tx in views:
        (out / "processes" / f"{tx['module']}.py").write_text(_render_process(tx))
        (out / "tests" / f"test_parity_{tx['module']}.py").write_text(_render_parity(tx))

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    ctx = {"process_name": ir.process_name, "transactions": views}
    (out / "pyproject.toml").write_text(env.get_template("pyproject.toml.j2").render(**ctx))
    (out / "README.md").write_text(env.get_template("README.md.j2").render(**ctx))

    (out / "__init__.py").write_text("")
    (out / "tests" / "__init__.py").write_text("")
    (out / "processes" / "__init__.py").write_text("")


# ---------------------------------------------------------------------------
# Python-file emitters
# ---------------------------------------------------------------------------


def _render_main(process_name: str, views: list[dict[str, Any]]) -> str:
    imports = "\n".join(f"from processes.{v['module']} import {v['fn_name']}" for v in views)
    calls = "\n".join(
        f'            logger.info("running {v["name"]}")\n'
        f"            await {v['fn_name']}(page, {{}})"
        for v in views
    )
    return f'''"""{process_name} — migrated from UiPath REFramework to Python + Playwright.

Entry point generated by rpa_architect.migrator. Queue-polling loops from
the REFramework are intentionally NOT replicated — the migration target is
behavior-equivalent code, not a drop-in Orchestrator substitute.

Env-var toggles (headed-by-default, persistent profile opt-in):

* ``RPA_HEADLESS=1`` — flip to headless (CI / scheduled runs).
* ``RPA_USER_DATA_DIR=/path`` — keep cookies + login between runs.
"""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path
from playwright.async_api import async_playwright

{imports}

logger = logging.getLogger("{process_name.lower()}")

_TRUTHY = {{"1", "true", "yes", "on"}}


def _headless_from_env(default: bool = False) -> bool:
    raw = os.environ.get("RPA_HEADLESS", "")
    return raw.strip().lower() in _TRUTHY if raw else default


def _user_data_dir_from_env() -> Path | None:
    raw = os.environ.get("RPA_USER_DATA_DIR", "").strip()
    return Path(raw).expanduser() if raw else None


async def main() -> None:
    headless = _headless_from_env()
    user_data_dir = _user_data_dir_from_env()
    async with async_playwright() as pw:
        if user_data_dir is not None:
            user_data_dir.mkdir(parents=True, exist_ok=True)
            context = await pw.chromium.launch_persistent_context(
                user_data_dir=str(user_data_dir),
                headless=headless,
            )
            browser = None
            page = context.pages[0] if context.pages else await context.new_page()
        else:
            browser = await pw.chromium.launch(headless=headless)
            context = await browser.new_context()
            page = await context.new_page()
        try:
{calls}
        finally:
            await context.close()
            if browser is not None:
                await browser.close()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
'''


def _render_process(tx: dict[str, Any]) -> str:
    body_lines: list[str] = []
    for step in tx["steps"]:
        body_lines.append(f"    # ── Step {step['id']}: {step.get('description') or step['type']} ──")
        for call in step["calls"]:
            body_lines.append(f"    {call}")
    body = "\n".join(body_lines) if body_lines else "    pass"

    return f'''"""{tx["name"]} — migrated from UiPath Process.xaml.

Generated by rpa_architect.migrator. Each action maps one UiPath UI activity
to its Playwright equivalent via the activity_map + selector_translator.
"""

from __future__ import annotations

import logging
from typing import Any

from playwright.async_api import Page

logger = logging.getLogger("{tx["module"]}")


async def {tx["fn_name"]}(page: Page, inputs: dict[str, Any]) -> dict[str, Any]:
    """Run the migrated {tx["name"]} flow on an already-open Playwright Page."""
    outputs: dict[str, Any] = {{}}
{body}
    return outputs
'''


def _render_parity(tx: dict[str, Any]) -> str:
    assertions: list[str] = []
    for sel in tx["selector_fingerprints"]:
        assertions.append(f"        # {sel['target']}")
        # Build the error message as a Python literal so any quotes inside the
        # CSS selector are properly escaped by repr().
        msg_literal = repr(
            f"selector {sel['css_literal']} for {sel['target']!r} no longer resolves"
        )
        assertions.append(
            f"        assert (await page.query_selector({sel['css_literal']})) is not None, "
            f"{msg_literal}"
        )
    assertion_block = "\n".join(assertions) if assertions else "        pass"

    return f'''"""Behavior-parity tests for {tx["name"]}."""

from __future__ import annotations

import os

import pytest
from playwright.async_api import async_playwright

from processes.{tx["module"]} import {tx["fn_name"]}  # noqa: F401 — imported to validate module

TARGET_URL = os.environ.get("TARGET_URL", "")
_TRUTHY = {{"1", "true", "yes", "on"}}
HEADLESS = os.environ.get("RPA_HEADLESS", "1").strip().lower() in _TRUTHY


@pytest.mark.asyncio
@pytest.mark.skipif(not TARGET_URL, reason="TARGET_URL not set; parity tests skipped")
async def test_{tx["module"]}_parity_all_selectors_resolve() -> None:
    """Every selector from the original XAML still resolves on TARGET_URL."""
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=HEADLESS)
        page = await browser.new_page()
        await page.goto(TARGET_URL)
{assertion_block}
        await browser.close()
'''


# ---------------------------------------------------------------------------
# view models
# ---------------------------------------------------------------------------


def _transaction_view(tx: Transaction) -> dict[str, Any]:
    module = _module_name(tx.name)
    return {
        "name": tx.name,
        "module": module,
        "fn_name": module,
        "steps": [_step_view(s) for s in tx.steps],
        "selector_fingerprints": [
            fp for step in tx.steps for fp in _selector_fingerprints(step.actions)
        ],
    }


def _step_view(step: Step) -> dict[str, Any]:
    calls: list[str] = []
    for action in step.actions:
        try:
            calls.append(emit_call(action))
        except UnsupportedActionError as exc:
            calls.append(f"# TODO: unsupported UiPath action: {exc}")
    return {
        "id": step.id,
        "description": step.description,
        "type": step.type,
        "calls": calls,
    }


def _selector_fingerprints(actions: list[UIAction]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for a in actions:
        if not a.selector_hint:
            continue
        expr = translate_selector(a.selector_hint)
        css = _extract_css(expr)
        if css is None:
            continue
        out.append({"target": a.target, "css_literal": repr(css)})
    return out


_LOCATOR_CSS_RE = re.compile(r"page\.locator\('([^']+)'\)")


def _extract_css(locator_expr: str) -> str | None:
    m = _LOCATOR_CSS_RE.search(locator_expr)
    return m.group(1) if m else None


_SNAKE_RE = re.compile(r"([A-Z])")


def _module_name(transaction_name: str) -> str:
    snake = _SNAKE_RE.sub(r"_\1", transaction_name).lower().lstrip("_")
    if not snake.startswith("process_"):
        snake = "process_" + snake
    return snake
