"""Generate Python code for AI agent nodes in Maestro workflows.

Each agent node is a UiPath Python SDK activity that calls the LLM gateway
with guardrail validation and optional human fallback.
"""

from __future__ import annotations

from rpa_architect.maestro.maestro_planner import AgentTaskDef

_AGENT_NODE_TEMPLATE = '''\
"""Agent node: {name}

Auto-generated by RPA Architect lifecycle agent.
Agent type: {agent_type}
Guardrails: {guardrails}
Fallback to human: {fallback}
"""

import json
import logging
from typing import Any

logger = logging.getLogger(__name__)


async def execute(
    input_data: dict[str, Any],
    context: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Execute the {agent_type} agent node.

    Args:
        input_data: Input data from the preceding workflow step.
        context: Optional workflow context (process variables, config).

    Returns:
        Agent output dict with 'result', 'confidence', and 'metadata' keys.
    """
    from rpa_architect.utils.llm_client import LLMClient

    client = LLMClient()

    system_prompt = _build_system_prompt(context or {{}})
    user_prompt = _build_user_prompt(input_data)

    response = await client.complete(
        system=system_prompt,
        prompt=user_prompt,
    )

    result = _parse_response(response)
    confidence = result.get("confidence", 0.0)

    # Apply guardrails
    guardrail_errors = _validate_guardrails(result)
    if guardrail_errors:
        logger.warning("Guardrail violations: %s", guardrail_errors)
        if {fallback_lower}:
            return {{
                "result": None,
                "confidence": 0.0,
                "requires_human_review": True,
                "guardrail_errors": guardrail_errors,
                "raw_response": response,
            }}

    # Check confidence threshold
    if confidence < {confidence_threshold}:
        logger.info("Confidence %.2f below threshold {confidence_threshold}", confidence)
        if {fallback_lower}:
            return {{
                "result": result.get("result"),
                "confidence": confidence,
                "requires_human_review": True,
                "reason": "Low confidence",
            }}

    return {{
        "result": result.get("result"),
        "confidence": confidence,
        "requires_human_review": False,
        "metadata": result.get("metadata", {{}}),
    }}


def _build_system_prompt(context: dict[str, Any]) -> str:
    """Build the system prompt for this agent type."""
    return (
        "You are an AI agent performing {agent_type} tasks within an enterprise automation workflow. "
        "Respond with valid JSON containing 'result', 'confidence' (0.0-1.0), and optional 'metadata'.\\n\\n"
        f"Workflow context: {{json.dumps(context, indent=2)}}"
    )


def _build_user_prompt(input_data: dict[str, Any]) -> str:
    """Build the user prompt from input data."""
    return f"Process the following input and provide your {agent_type} output:\\n\\n{{json.dumps(input_data, indent=2)}}"


def _parse_response(response: str | Any) -> dict[str, Any]:
    """Parse LLM response into structured output."""
    text = response if isinstance(response, str) else str(response)
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]
    try:
        return json.loads(text.strip())
    except json.JSONDecodeError:
        return {{"result": text.strip(), "confidence": 0.5}}


def _validate_guardrails(result: dict[str, Any]) -> list[str]:
    """Validate agent output against configured guardrails."""
    errors: list[str] = []
    guardrails = {guardrails_repr}

    for guard in guardrails:
        if guard == "non_empty" and not result.get("result"):
            errors.append("Result must not be empty")
        elif guard == "valid_json":
            if not isinstance(result.get("result"), (dict, list)):
                errors.append("Result must be valid JSON object or array")
        elif guard == "high_confidence" and result.get("confidence", 0) < 0.9:
            errors.append("Confidence must be >= 0.9 for this guardrail")

    return errors
'''


def generate_agent_node_code(task_def: AgentTaskDef) -> str:
    """Generate Python source code for an agent node.

    Args:
        task_def: The AgentTaskDef from the Maestro planner.

    Returns:
        Python source code string for the agent node module.
    """
    return _AGENT_NODE_TEMPLATE.format(
        name=task_def.name,
        agent_type=task_def.agent_type,
        guardrails=", ".join(task_def.guardrails) or "none",
        fallback=task_def.fallback_to_human,
        fallback_lower=str(task_def.fallback_to_human).lower(),
        confidence_threshold=task_def.confidence_threshold,
        guardrails_repr=repr(task_def.guardrails),
    )


def generate_agent_nodes_for_plan(
    tasks: list[AgentTaskDef],
) -> dict[str, str]:
    """Generate Python agent node files for all agent tasks in a Maestro plan.

    Args:
        tasks: List of AgentTaskDef from the planner.

    Returns:
        Dict mapping filename → Python source code.
    """
    files: dict[str, str] = {}
    for task in tasks:
        filename = f"agent_{task.task_id.lower()}.py"
        files[filename] = generate_agent_node_code(task)
    return files
