"""Test case generation for UiPath coded test projects.

Generates C# coded test files using Jinja2 templates, producing
[TestCase]-annotated methods that exercise the generated workflows.
"""

from __future__ import annotations

import logging
from typing import Any, Literal, Protocol, runtime_checkable

from pydantic import BaseModel, Field

from rpa_architect.ir.schema import ProcessIR

# Import GeneratedFile directly from the module to avoid pulling in
# langgraph via codegen/__init__.py at import time.
try:
    from rpa_architect.codegen.orchestrator import GeneratedFile
except ImportError:
    # Fallback definition if langgraph is not installed
    class GeneratedFile(BaseModel):  # type: ignore[no-redef]
        """A single generated file in the UiPath project."""
        path: str
        content: str
        file_type: str
        generation_task_id: str
from rpa_architect.testing.scenario_builder import TestScenario, build_scenarios

logger = logging.getLogger(__name__)


class TestCaseSpec(BaseModel):
    """Specification for a single generated test case."""

    name: str = Field(description="Test method name (PascalCase).")
    description: str = Field(description="What the test verifies.")
    test_type: Literal["unit", "integration", "e2e"] = Field(
        description="Test granularity level.",
    )
    setup_steps: list[str] = Field(
        default_factory=list,
        description="Setup steps to run before the test body.",
    )
    assertions: list[str] = Field(
        default_factory=list,
        description="Assertion statements to include in the test.",
    )


@runtime_checkable
class LLMClient(Protocol):
    """Protocol for an LLM client used to enhance test generation."""

    async def create_message(
        self,
        *,
        messages: list[dict[str, Any]],
        model: str,
        max_tokens: int,
    ) -> Any: ...


_CODED_TESTCASE_TEMPLATE = """\
// Auto-generated test file for {{ process_name }}
// Generated by Autonomous RPA Architect

using System;
using System.Collections.Generic;
using UiPath.CodedWorkflows;
using UiPath.CodedWorkflows.Testing;

namespace {{ namespace }}.Tests
{
    /// <summary>
    /// Test cases for the {{ process_name }} RPA process.
    /// </summary>
    public class {{ test_class_name }} : CodedTestCase
    {
{% for test in test_cases %}
        /// <summary>
        /// {{ test.description }}
        /// </summary>
        [TestCase]
        public void {{ test.name }}()
        {
{% for setup in test.setup_steps %}
            // Setup: {{ setup }}
{% endfor %}

            // TODO: Implement test body
            // Test type: {{ test.test_type }}

{% for assertion in test.assertions %}
            // Assert: {{ assertion }}
{% endfor %}
{% if not test.assertions %}
            // TODO: Add assertions
            throw new NotImplementedException("Test '{{ test.name }}' needs implementation.");
{% endif %}
        }

{% endfor %}
    }
}
"""


def _scenario_to_test_spec(scenario: TestScenario) -> TestCaseSpec:
    """Convert a TestScenario into a TestCaseSpec."""
    # Determine test type from path type
    test_type_map: dict[str, Literal["unit", "integration", "e2e"]] = {
        "happy": "e2e",
        "business_exception": "integration",
        "system_exception": "integration",
        "edge_case": "unit",
    }

    test_type = test_type_map.get(scenario.path_type, "integration")

    # Build assertions from expected outcome
    assertions: list[str] = []
    if scenario.expected_outcome:
        assertions.append(f"Verify: {scenario.expected_outcome}")

    if scenario.path_type == "business_exception":
        assertions.append("Assert.ThrowsException<BusinessRuleException>(action)")
    elif scenario.path_type == "system_exception":
        assertions.append("Assert.IsTrue(retryCount <= MaxRetryNumber)")

    return TestCaseSpec(
        name=scenario.name.replace(" ", "_"),
        description=scenario.description,
        test_type=test_type,
        setup_steps=scenario.steps,
        assertions=assertions,
    )


def _sanitize_class_name(name: str) -> str:
    """Convert a process name to a valid C# class name."""
    sanitized = "".join(c if c.isalnum() else "_" for c in name)
    sanitized = sanitized.strip("_")
    if sanitized and sanitized[0].isdigit():
        sanitized = f"Test_{sanitized}"
    return f"{sanitized}Tests"


def _render_test_file(
    process_name: str,
    test_cases: list[TestCaseSpec],
) -> str:
    """Render the coded test case file from specs."""
    try:
        from jinja2 import Environment

        env = Environment(
            keep_trailing_newline=True,
            trim_blocks=True,
            lstrip_blocks=True,
        )
        template = env.from_string(_CODED_TESTCASE_TEMPLATE)
    except ImportError:
        # Fallback to simple string formatting if Jinja2 unavailable at import
        logger.warning("Jinja2 not available; using basic template rendering.")
        return _render_test_file_basic(process_name, test_cases)

    namespace = process_name.replace(" ", "").replace("-", "")
    test_class_name = _sanitize_class_name(process_name)

    return template.render(
        process_name=process_name,
        namespace=namespace,
        test_class_name=test_class_name,
        test_cases=test_cases,
    )


def _render_test_file_basic(
    process_name: str,
    test_cases: list[TestCaseSpec],
) -> str:
    """Fallback renderer without Jinja2."""
    namespace = process_name.replace(" ", "").replace("-", "")
    test_class_name = _sanitize_class_name(process_name)

    lines = [
        f"// Auto-generated test file for {process_name}",
        "using System;",
        "using UiPath.CodedWorkflows;",
        "using UiPath.CodedWorkflows.Testing;",
        "",
        f"namespace {namespace}.Tests",
        "{",
        f"    public class {test_class_name} : CodedTestCase",
        "    {",
    ]

    for tc in test_cases:
        lines.append(f"        /// <summary>{tc.description}</summary>")
        lines.append("        [TestCase]")
        lines.append(f"        public void {tc.name}()")
        lines.append("        {")
        lines.append('            throw new NotImplementedException("Test needs implementation.");')
        lines.append("        }")
        lines.append("")

    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


async def generate_tests(
    ir: ProcessIR,
    generated_files: dict[str, GeneratedFile],
    llm_client: Any,
) -> list[GeneratedFile]:
    """Generate coded C# test files for the RPA process.

    Analyzes the IR to build test scenarios, converts them to test specs,
    and renders C# test files using Jinja2 templates.

    Args:
        ir: The ProcessIR describing the process under test.
        generated_files: Already-generated project files (for context).
        llm_client: LLM client for optional test enhancement (unused in
            basic generation; reserved for future LLM-assisted assertion
            generation).

    Returns:
        List of GeneratedFile objects containing the test C# files.
    """
    scenarios = build_scenarios(ir)

    if not scenarios:
        logger.info("No test scenarios generated (no transactions in IR).")
        return []

    test_specs = [_scenario_to_test_spec(s) for s in scenarios]

    # Render test file
    content = _render_test_file(ir.process_name, test_specs)
    test_class_name = _sanitize_class_name(ir.process_name)
    file_path = f"Tests/{test_class_name}.cs"

    test_file = GeneratedFile(
        path=file_path,
        content=content,
        file_type="cs",
        generation_task_id="test_generator",
    )

    logger.info(
        "Generated %d test cases in %s.",
        len(test_specs),
        file_path,
    )

    return [test_file]
